# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bc42644f8542fce48707f53bb5ad0717f64da3830e02ce7570f5e166e96dfafa3988c9c3ab05130c79399e8cb38b99b298cf48f0f05c5df24a63f2b7159e85

test:
  secret_key_base: bd778f43d5da51a0f89c661087281fdd8deb3bfb02994ff1b8f03dcda89d09add5a1bf3552a0185c59300ac5e10c39ad732316b001a1659c01a8e60021849887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
